version: "3"

services:
  app:
    image: poongdeong-server
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    environment:
    - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE=${DATABASE}
    depends_on:
      - db

  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - db

  db:
    image: mariadb:10.4.8
    ports:
      - '3306:3306'
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_HOST=%
