name: Server CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: poongdeong_test
          mysql root password: root1234
          mysql user: 'root'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test -- --coverage
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Set Env
        if: github.ref == 'refs/heads/master'
        run: |
          echo ::set-env name=IMAGE::poongdeong-server
      - name: Docker build
        if: github.ref == 'refs/heads/master'
        run: |
          docker build -t $IMAGE .
      - name: ECR push
        if: github.ref == 'refs/heads/master'
        run: |
          $(aws ecr get-login --no-include-email --region ap-northeast-2)
          docker tag $IMAGE $REPO/$IMAGE:${GITHUB_SHA::7}
          docker push $REPO/$IMAGE:${GITHUB_SHA::7}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SERVER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SERVER_AWS_SECRET_ACCESS_KEY }}
          REPO: 964037622278.dkr.ecr.ap-northeast-2.amazonaws.com
